ALTER TABLE PL_COMPETITION ADD COLUMN (DEFAULTTOURNAMENTDEADLINE INTEGER)
UPDATE PL_COMPETITION SET DEFAULTTOURNAMENTDEADLINE = 8
ALTER TABLE PL_COMPETITION DROP COLUMN DEFAULTTOURNAMENTANNOUNCEMENTLEAD
ALTER TABLE PL_TOURNAMENT ADD COLUMN (DEADLINE INTEGER)
UPDATE PL_TOURNAMENT SET DEADLINE = 8
ALTER TABLE PL_TOURNAMENT DROP COLUMN TOURNAMENTANNOUNCEMENTLEAD
ALTER TABLE PL_INVITATIONEVENT DROP FOREIGN KEY FK_PL_INVITATIONEVENT_INVITATION_ID
DROP TABLE PL_INVITATIONEVENT
